# Generated by Django 2.0.5 on 2018-07-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180701_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='sub_goals',
            field=models.ManyToManyField(blank=True, to='core.Goal'),
        ),
    ]
