# Generated by Django 2.0.5 on 2018-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180701_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='begin',
            field=models.DateField(auto_now=True),
        ),
    ]
