# Generated by Django 2.0.5 on 2018-07-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180704_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Goal'),
        ),
    ]
