# Generated by Django 2.0.5 on 2018-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180704_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='goals',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
