# Generated by Django 2.0.5 on 2018-07-05 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20180704_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('begin', models.TimeField(default=datetime.datetime(2018, 7, 5, 19, 33, 51, 27983, tzinfo=utc))),
                ('end', models.TimeField(default=datetime.datetime(2018, 7, 5, 19, 33, 51, 28189, tzinfo=utc))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('begin',),
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-date', 'time')},
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='begin',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 19, 33, 51, 11917, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='core.Task'),
        ),
    ]
